name: Multi Platform Test
on:
  pull_request:
    branches: [ main ]

jobs:
  ubuntu-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Show OS info
        run: uname -a
      - name: Create file
        run: echo "Hello from Ubuntu" > note.txt
      - name: Show file
        run: cat note.txt

  windows-job:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show OS info
        run: ver
        shell: cmd

      - name: Create file
        run: echo Hello from Windows > note.txt
        shell: cmd

      - name: Show file
        run: type note.txt
        shell: cmd

  macos-job:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Show OS info
        run: uname -a
      - name: Create file
        run: echo "Hello from macOS" > note.txt
      - name: Show file
        run: cat note.txt
