jobs:
  ubuntu-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Show OS info
        run: uname -a
      - name: Create and show file
        run: |
          echo "Hello from Ubuntu" > note.txt
          cat note.txt

  windows-job:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Show OS info
        run: systeminfo
      - name: Create and show file
        run: |
          echo Hello from Windows > note.txt
          type note.txt

  macos-job:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Show OS info
        run: uname -a
      - name: Create and show file
        run: |
          echo "Hello from macOS" > note.txt
          cat note.txt
